############################# Makefile ##########################
CC = g++
CTARGET = src/main.cpp
EXECNAME = teste

all: 
	$(CC) -o $(EXECNAME) $(CTARGET)
	./teste
	
clean: $(RM) $(teste.exe)