############################# Makefile ##########################
CC = g++
CTARGET = src/main.cpp
EXECNAME = teste

all: 
	$(CC) -o $(EXECNAME) $(CTARGET)
	./teste a5b90c1a2b5e3a014253698745214523 > teste.txt
	
clean: $(RM) $(teste.exe)