############################# Makefile ##########################
CC = g++
CTARGET = src/main.cpp
EXECNAME = teste

all: 
	$(CC) -o $(EXECNAME) $(CTARGET)
	@echo "Execute using: ./teste {-c, -d} tests/<FILE>.txt"
	
clean: $(RM) $(teste.exe)