############################# Makefile ##########################
CC = g++
CTARGET = src/main.cpp
EXECNAME = vigenere

all: 
	$(CC) -o $(EXECNAME) $(CTARGET)
	@echo "Execute using: ./vigenere {-c, -d} tests/<FILE>.txt"
	
clean: $(RM) $(vigenere.exe)