############################# Makefile ##########################
CC = g++
CTARGET = main.cpp
EXECNAME = vigenere.exe

all: 
	$(CC) -o $(EXECNAME) $(CTARGET)
	@echo "Execute using: ./vigenere.exe {-c, -d} <PATH_TO_FILE>"
	
clean: $(RM) $(vigenere.exe)